[package]
authors = ["Sam Rose <sam@cvpartner.com>"]
edition = "2018"
name = "rust-debugger"
version = "0.1.0"

[dependencies]
human-panic = "*"
libc = "0.2"
rustyline = "6.1.1"
log = "0.4.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"